name: dart_tkui
description: dart bindings to Tcl/Tk over FFI.
version: 1.0.0
homepage: https://github.com/insinfo/tcltk_bindings

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: '>=1.1.2 <3.0.0'
  image: ^4.0.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.2
  ffigen: any #^2.4.2
  http: any
 # lint: ^2.0.0
#dart run ffigen --config ffigen.yaml